name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5   # обновлено с v4 до v5

    - name: Set up Python
      uses: actions/setup-python@v5  # остаётся v5, если предупреждение не уйдёт, замените на @v6 при наличии
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "AssetManager" main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AssetManager-Windows
        path: dist/AssetManager.exe
